const partnersData = {
  1: {
    adsoyad: "kucu ucuc",
    yaş: "23",
    boy: "232",
    cinsiyet: "erkek",
    şehir: "istanbul",
    açıklama: "kral aadam",
    phoneNumber: "+905347793580",
    folderNumber: "1",
  },
  2: {
    adsoyad: "maks",
    yaş: "23",
    boy: "232",
    cinsiyet: "kadın",
    şehir: "istanbul",
    açıklama: "kral adamw",
    phoneNumber: "+905347793580",
    folderNumber: "2",
  },
  3: {
    adsoyad: "meme ben",
    yaş: "34",
    boy: "343",
    cinsiyet: "kadın",
    şehir: "istanbul",
    açıklama: "Template repositories let users generate new repositories with the same",
    phoneNumber: "+905347793580",
    folderNumber: "3",
  },
  4: {
    adsoyad: "baba pro",
    yaş: "343",
    boy: "180",
    cinsiyet: "erkek",
    şehir: "ankara",
    açıklama: "5347793580",
    phoneNumber: "+905347793580",
    folderNumber: "4",
  },
  5: {
    adsoyad: "Pandorama",
    yaş: "25",
    boy: "150",
    cinsiyet: "erkek",
    şehir: "gaziantep",
    açıklama: "En güzel esc benim",
    phoneNumber: "+905347793580",
    folderNumber: "5",
  },
};